### ISSUE TITLE
Handle bad data

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#181]
Feedback Received: "Feature request: having a way to define assertions/validations and what happens when you get bad data"

**Comment by thanosqr** [comment]
Hey Miguel!

So the example in the tutorial,
```
 - Name: games_played
       Type: integer
       When: source.event_id == 'game_start'
       Value: session_stats.games_played + 1

- Name: games_won
       Type: integer
       When: source.event_id == 'game_end' and source.won == '1'
       Value: session_stats.games_won + 1
```

will turn
```

1 { "user_id": "09C1", "session_id": "915D", "country" : "US", "event_id": "game_start" }
2 { "user_id": "09C1", "session_id": "915D", "country" : "US", "event_id": "game_end", "won": 1 }
3 { "user_id": "09C1", "session_id": "915D", "country" : "US", "event_id": "game_start" }
4 { "user_id": "09C1", "session_id": "915D", "country" : "US", "event_id": "game_end", "won": 1 }

```

into `915D    09C1    2    2`

But what happens if row 3 is missing? I'm assuming that games_played will stay 1 and games_won will be 2.  The user might instead want to remove the session from the results or have an error message. Note that in this case we can see that the result is wrong in its end state, so we could catch it by doing a check after processing. But sometimes it can only be detected while processing, e.g. if rows 1 and 4 are missing.

Implementation-wise, my first thought was to be able to define something like:

```
- Name: games_won
       Type: integer
       When: source.event_id == 'game_end' and source.won == '1'
       Value: session_stats.games_won + 1
       AssertBefore: session_stats.games_played > session_stats.games_won
--or
       AssertAfter: session_stats.games_played >= session_stats.games_won
       IfError: ignore session_id
```

But it can get a bit messy. Then I thought, an assert is pretty much the same as `When`, so we could add a field like this:

```
- Name: cannot_win_more_than_played
       Type: integer
       When: session_stats.games_played > session_stats.games_won
       Value: session_stats.cannot_win_more_than_played + 1
```

or perhaps, to avoid have lots of validation fields:
```
- Name: game_validation
       Type: error_map
       When1: session_stats.games_played > session_stats.games_won
       Value1: "fewer games_played than games_won"

       When2: ...
       Value2: ""
```
the error_map type should evaluate to true if there were any errors and have the count of the different errors as entries but it changes the general structure.

If the user can rely on the order of field declaration for the order of evaluation, the second form of validations doesn't need any changes; otherwise, there needs to be a way to know whether a validation runs before or after the event is read (could be that all validations are always run afterwards).

Hope it makes sense!

**Comment by prashastk** [comment]
Thanks for the detailed explanation @thanosqr !

Maintaining session state across multiple events is a tricky problem because we don't want to assume any specific ordering of events. An event missing right now may arrive a bit later because of network issues.

One possible way of determining the correctness of a session (without relying on the order of events) could be done with:

```
- Name: game_start_and_end
  Type: list
  Value: session_stats.game_start_and_end.add((time, source.event_id))
  When: source.event_id == 'game_start' or source.event_id == 'game_end' 
```
Then another field can be defined to determine the correctness:
```
-  Name: valid_session
  Type: boolean
  Value: valid_start_and_end(session_stats.game_start_and_end)
  When: source.event_id == 'game_start' or source.event_id == 'game_end' 
```
```
def valid_start_and_end(games_list):
  # Determine that each game_start has a corresponding game_end.
  # and return True / False accordingly.
```
As more events are processed the value of session_stats.valid_session will maintain whether this session is valid or not. The fields are evaluated in the order they are defined so the valid_session field should be defined after game_start_and_end field.

This needs custom function support which is coming very soon :)

Do you think this is a good way to handle this?

**Comment by thanosqr** [comment]
Yep, sounds good (also +1 for custom functions)!

Something I  forgot to mention; a validation doesn't have to be about a session, in fact I'd expect that most of them would be about the event format, e.g. missing fields, In those cases it would be nice to be able to reuse a field in fields defined after it (maybe it's possible already), e.g.:

```
-Name: valid_event
(...)
When: valid_event and ...
```
Tbh I'm not sure what's the most elegant solution to this, merely mentioning the pattern :)

**Comment by prashastk** [comment]
There are multiple ways to handle a per event validation.
- Create a variable (`VariableAggregate`) with the required clean up on the event field and then use that variable.
- Use `When` in `Field` for validation conditions.
- Define a `valid_event` field (as you mentioned) and use that in `When`. This can be go in `VariableAggregate` if you don't want to save it.
- If its ok to ignore fields that have errors (e.g. missing) you can choose to do nothing and blurr already handles this. In case of missing event fields in source the `Field` evaluation that uses it will be skipped and an error is logged in debug logs.

**Comment by roy100** [comment]
Thank you @thanosqr for the feedback! We have turned this into some documentation in the hope that such a discussion will be useful. PR is here: https://github.com/productml/blurr/pull/211

Do you think we should close this issue?

**Comment by thanosqr** [comment]
@roy100 cool! yeah looks good from my end
