### ISSUE TITLE
Consider Snapshot Test for Store State tests

### ISSUE THREAD

**Issue by indradeep** [productml/blurr#209]
Several places in the Blurr unit tests that test the state of the store.

@mserranom suggested that we look at [Snapshot Test](https://github.com/syrusakbary/snapshottest).

We need to evaluate how Snapshot test will work for our use case and adopt it if it fits.

**Comment by mserranom** [comment]
The specific case I commented was this:

```python
assert store_state.get(Key('user1', 'label_aggr.None')) == {
        '_identity': 'user1',
        '_label': 'None',
        '_start_time': datetime(2018, 1, 1, 1, 1, 1, 0, timezone.utc),
        '_end_time': datetime(2018, 1, 1, 1, 1, 5, 0, timezone.utc),
        'sum': 110,
        'count': 2
 }
```

When a file have multiple assertions like this it difficults readabilit.  Plus we're not really testing behaviour here, just shape of plain objects.

For this cases, snapshot testing is more concise:

```python
snapshot.assert_match(
                 store_state.get(Key('user1', 'label_aggr.None')))
```

**Comment by prashastk** [comment]
I don't like snapshot testing for such assertions because it moves the expected behavior to a separate file. Any test that is setting up the scenario for testing in the test file should also contain the expected behavior.

IMO snapshot testing should be used where the test scenario setup is also coming from an external location and the test itself is not changing anything. For e.g. if the test takes in a dtc file, raw data and the expected output.
