### ISSUE TITLE
Spec for revamped validation

### ISSUE THREAD

**Issue by mserranom** [productml/blurr#254]
#### Issue Checklist:
- [x] Descriptive title
- [x] Completed sections below

# Problem Description

We've dismissed Yamale as the tool to validate YAML format. We need line information and customised error messages. This document is the spec for the new validation system.

# Solution Proposal

##  Error Message Format

Each error message will print the line number and an excerpt of the content:

Template:
```
<FILE_PATH>:<LINE_NUMBER> -> <BLOCK_PATH>
<ERROR_MESSAGE>
```

Examples: 
```
./stream.yml:8: -> /Time
invalid python expression

./stream.yml:34: -> /Aggregates/Fields[3]
missing required property "Type"
```

## Errors

**Missing property**

```
./stream.yml:34: -> /Aggregates/Fields[3]
missing required property "Type"
```

**Missing block**

```
./stream.yml:0: -> /
missing required block "Aggregates"
```

**Invalid property**

```
./stream.yml:34: -> /Aggregates/Fields[3]/Tyyype
"Tyyype" is not a valid property 
```

**Invalid block**

```
./stream.yml:28: -> /Aggggregates
"Aggggregates" is not a valid block
```

**Invalid Data Type**

```
./stream.yml:36: -> /Aggregates/Fields[3]/Type
"blah" is not a valid data type 
```

**Invalid Identifier**

```
./stream.yml:35: -> /Aggregates/Fields[3]/Name
"n@me" is not a valid identifier
```
**Reserver Keyword**

```
./stream.yml:35: -> /Aggregates/Fields[3]/Name
"n@me" is not a valid identifier
```

**Invalid Python Expression**

Apart from the message, we'll print the output from Python syntax check:

```
./stream.yml:38: -> /Aggregates/Fields[3]/Value
invalid python expression:
   | <PYTHON_OUTPUT
   | <PYTHON_OUTPUT
```

# Impact on current behavior

The refactored validation will be disabled by default until implementation is complete. In the meantime, Yamale validation will be used, and there will be an available flag to use the new implementation.

**Comment by indradeep** [comment]
## Design Principles
### Proximity of validation to schema definition 
**Current Limitation**

The `yamale` validation system requires schema spec validation to be specified outside of the schema definition block.  Any new schema written would require modification in two places.  

Custom extensions written outside the Blurr library have no access to the `yamale` validator and will not be able to add validation for custom types.

**Proposed Solution**

Validation should be designed such that schema definition and validation code must reside together.  This ensures cleaner extensibility in that all future schemas that are added either directly into Blurr library, or as single-purpose extensions, can declare their validation in the same module / class they write. 

### Separation of error representation in system vs. how errors are presented to the user. 

**Current Limitation**

When errors are found in the system, an exception broadly categorizing the nature of the error is raised with a message that detail the error.  Since the specifics of the entities / sections involved are all represented in the predefined exception message, there is no scope for reorganizing the error for better presentation.

**Proposed Solution**

Errors raised by Blurr must contain sufficient structure to represent the following:
- Nature of violation
- References to parties involved
- String representaiton of the message for default debug / print

This will allow errors to be organized and represnted in different ways before they are displayed to the user for providing greatst clarity.

### Providing the most complete feedback possible with every execution

**Current Limitation**

Outisde of the `yamale` validation with its cryptic feedback, all exceptions in Blurr are raised as exceptional conditions are encountered.  Consequently,only one critical error surfaces at a time for the user to fix.  This makes debugging painful.

**Proposed Solution**

Errors raised should be collected at a high-enough level such that a full report of all errors that were raised during a run can be shared with the user.  

### Makeing errors readable
**Current Limitation**

The current error messages are cryptic and contain little context for a user to easily trace the error back to the part of the Blurr Transform Spec.

**Proposed Solution**

To aid the developer with tracing:

1. Provide context using schema elements and values
2. Provide line number in the BTS YAML file
